name: bluefin 40
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - '**.md'
      - 'system_files/kinoite/**'
  schedule:
    - cron: '40 16 * * *'  # 16:40 UTC everyday
  workflow_dispatch:

jobs:
  build-base:
    name: build-base
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: 40
      target_version: base
  build-dx:
    name: build-dx
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: 40
      target_version: dx